routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Auth::routes();
Route::resource('/', 'DashboardController');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('home', 'HomeController');

    //admin
    Route::group(['prefix' => 'admin', 'middleware' => ['role:admin'], 'as' => 'admin.'], function () {
        Route::post('logout', 'Admin\DashboardController@logout')->name('logout');
        Route::resource('dashboard', 'Admin\DashboardController');

        Route::name('manages.')->group(function () {
            Route::resource('manages/course', 'Admin\Manages\CourseController');
            Route::resource('manages/course.detail', 'Admin\Manages\CourseDetailController');
            Route::resource('manages/bill', 'Admin\Manages\BillController');
            Route::resource('manages/profile', 'Admin\Manages\ProfileController');
            Route::resource('manages/student', 'Admin\Manages\StudentController');
            Route::resource('manages/comment', 'Admin\Manages\CommentController');

        });
    });

    //user
    Route::group(['prefix' => 'user', 'middleware' => ['role:user|admin'], 'as' => 'user.'], function () {
        Route::resource('dashboard', 'User\DashboardController');
        Route::resource('course', 'User\CourseController');
        Route::resource('buy', 'User\BuyController');
        Route::resource('bill', 'User\BillController');
        Route::resource('status', 'User\StatusController');
        Route::resource('mycourse', 'User\MycourseController');
        Route::resource('class', 'User\ClassController');
        Route::resource('cart', 'User\CartController');
        Route::resource('study', 'User\StudyController');
        Route::resource('profile', 'User\ProfileController');
    });
});

resources/views/includes/main/alert.blade.php
@if(session()->has('message'))
    <div class="alert alert-success">
        {{ session()->get('message') }}
    </div>
@endif

resources/views/includes/main/footer.blade.php
<div class="footer">
    <div class="pull-right">
        10GB of <strong>250GB</strong> Free.
    </div>
    <div>
        <strong>Copyright</strong> Example Company &copy; 2014-2017
    </div>
</div>

resources/views/includes/main/header.blade.php
<div class="row border-bottom">
        <nav class="navbar navbar-static-top " role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i></a>
            </div>
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle count-info" data-toggle="dropdown" href="#">
                        <i class="fa fa-bell"></i> <span class="label label-primary">8</span>
                    </a>
                    <ul class="dropdown-menu dropdown-alerts">
                        <li>
                            <a href={{route('admin.manages.comment.index')}}>
                                <div>
                                    <i class="fa fa-comments fa-fw"></i>ได้รับ 6 ความคิดเห็น
                                    <span class="pull-right text-muted small">4 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href={{route('admin.manages.bill.index')}}>
                                <div>
                                    <i class="fa fa-pencil-square-o fa-fw"></i>2 คำขออนุมัติการชำระเงิน
                                    <span class="pull-right text-muted small">12 minutes ago</span>
                                </div>
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <div class="text-center link-block">
                                <a href="notifications.html">
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
                <li>
                     <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        <i class="fa fa-sign-out"></i> ออกจากระบบ
                    </a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </li>
            </ul>

        </nav>
    </div>

resources/views/includes/main/navigation.blade.php
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element"> <span>
                        <img alt="image" class="img-circle" src="{{asset('/inspinia/img/profile_small.jpg')}}" />
                    </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                        <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold"></strong>
                            </span> <span class="text-muted text-xs block">{{Auth::user()->name}} <b class="caret"></b></span>
                        </span> </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href={{route('admin.manages.profile.index')}}>โปรไฟล์</a></li>
                        
                        
                        <li class="divider"></li>
                        <li>
                            <a onclick="event.preventDefault();  document.getElementById('logout-form').submit();">
                                <i class="fa fa-sign-out"></i> ออกจากระบบ
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>


            <li>
                <a href="index.html"><i class="fa fa-th-large"></i>จัดการ <span class="nav-label"></span> <span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li><a href="{{route('admin.manages.course.index')}}">คอร์สเรียน</a></li>
                    <li><a href="{{route('admin.manages.bill.index')}}">อนุมัติการชำระเงิน</a></li>
                    <li><a href="{{route('admin.manages.student.index')}}">รายชื่อผู้เรียน</a></li>
                </ul>
            </li>
        </ul>
    </div>

resources/views/includes/main/script.blade.php
<script src="{{asset('inspinia/js/jquery-3.1.1.min.js')}}"></script>
<script src="{{asset('inspinia/js/bootstrap.min.js')}}"></script>
<script src="{{asset('inspinia/js/plugins/metisMenu/jquery.metisMenu.js')}}"></script>
<script src="{{asset('inspinia/js/plugins/slimscroll/jquery.slimscroll.min.js')}}"></script>

<!-- Custom and plugin javascript -->
<script src="{{asset('inspinia/js/inspinia.js')}}"></script>
<script src="{{asset('inspinia/js/plugins/pace/pace.min.js')}}"></script>

resources/views/includes/main/style.blade.php
<link href="{{asset('inspinia/css/bootstrap.min.css')}}" rel="stylesheet">
<link href="{{asset('inspinia/font-awesome/css/font-awesome.css')}}" rel="stylesheet">
<link href="{{asset('inspinia/css/animate.css')}}" rel="stylesheet">
<link href="{{asset('inspinia/css/style.css')}}" rel="stylesheet">