routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Auth::routes();
Route::resource('/', 'DashboardController');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('home', 'HomeController');

    //admin
    Route::group(['prefix' => 'admin', 'middleware' => ['role:admin'], 'as' => 'admin.'], function () {
        Route::post('logout', 'Admin\DashboardController@logout')->name('logout');
        Route::resource('dashboard', 'Admin\DashboardController');

        Route::name('manages.')->group(function () {
            Route::resource('manages/course', 'Admin\Manages\CourseController');
            Route::resource('manages/course.detail', 'Admin\Manages\CourseDetailController');
            Route::resource('manages/bill', 'Admin\Manages\BillController');
            Route::resource('manages/profile', 'Admin\Manages\ProfileController');
            Route::resource('manages/student', 'Admin\Manages\StudentController');
            Route::resource('manages/comment', 'Admin\Manages\CommentController');

        });
    });

    //user
    Route::group(['prefix' => 'user', 'middleware' => ['role:user|admin'], 'as' => 'user.'], function () {
        Route::resource('dashboard', 'User\DashboardController');
        Route::resource('course', 'User\CourseController');
        Route::resource('buy', 'User\BuyController');
        Route::resource('bill', 'User\BillController');
        Route::resource('status', 'User\StatusController');
        Route::resource('mycourse', 'User\MycourseController');
        Route::resource('class', 'User\ClassController');
        Route::resource('cart', 'User\CartController');
        Route::resource('study', 'User\StudyController');
        Route::resource('profile', 'User\ProfileController');
    });
});

app/Http/Controllers/Admin/Manages/StudentController.php
<?php

namespace App\Http\Controllers\Admin\Manages;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.admin.student.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('pages.admin.student.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/admin/student/index.blade.php
@extends('layouts.admin.main')

@section('list')
<div class="col-sm-12">
    <h2>รายชื่อผู้เรียนทั้งหมด</h2>
    <ol class="breadcrumb">
        <li>
            <a>จัดการ</a>
        </li>
        <li class="active">
            <strong>รายชื่อผู้เรียน</strong>
        </li>
    </ol>
</div>
@endsection

@section('style')

@endsection

@section('content')
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-4">
            <div class="contact-box">
                <a href="{{route('admin.manages.student.show',2)}}">
                    <div class="col-sm-4">
                        <div class="text-center">
                            <img alt="image" class="img-circle m-t-xs img-responsive" src="img/a2.jpg">
                            <div class="m-t-xs font-bold">Graphics designer</div>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <h3><strong>John Smith</strong></h3>
                        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
                        <address>
                            <strong>Twitter, Inc.</strong><br>
                            795 Folsom Ave, Suite 600<br>
                            San Francisco, CA 94107<br>
                            <abbr title="Phone">P:</abbr> (123) 456-7890
                        </address>
                    </div>
                    <div class="clearfix"></div>
                </a>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="contact-box">
                 <a href="{{route('admin.manages.student.show',2)}}">
                    <div class="col-sm-4">
                        <div class="text-center">
                            <img alt="image" class="img-circle m-t-xs img-responsive" src="img/a1.jpg">
                            <div class="m-t-xs font-bold">CEO</div>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <h3><strong>Alex Johnatan</strong></h3>
                        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
                        <address>
                            <strong>Twitter, Inc.</strong><br>
                            795 Folsom Ave, Suite 600<br>
                            San Francisco, CA 94107<br>
                            <abbr title="Phone">P:</abbr> (123) 456-7890
                        </address>
                    </div>
                    <div class="clearfix"></div>
                </a>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="contact-box">
                 <a href="{{route('admin.manages.student.show',2)}}">
                    <div class="col-sm-4">
                        <div class="text-center">
                            <img alt="image" class="img-circle m-t-xs img-responsive" src="img/a3.jpg">
                            <div class="m-t-xs font-bold">Marketing manager</div>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <h3><strong>Monica Smith</strong></h3>
                        <p><i class="fa fa-map-marker"></i> Riviera State 32/106</p>
                        <address>
                            <strong>Twitter, Inc.</strong><br>
                            795 Folsom Ave, Suite 600<br>
                            San Francisco, CA 94107<br>
                            <abbr title="Phone">P:</abbr> (123) 456-7890
                        </address>
                    </div>
                    <div class="clearfix"></div>
                </a>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')

@endsection

resources/views/pages/admin/student/show.blade.php
...