routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Auth::routes();
Route::resource('/', 'DashboardController');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('home', 'HomeController');

    //admin
    Route::group(['prefix' => 'admin', 'middleware' => ['role:admin'], 'as' => 'admin.'], function () {
        Route::post('logout', 'Admin\DashboardController@logout')->name('logout');
        Route::resource('dashboard', 'Admin\DashboardController');

        Route::name('manages.')->group(function () {
            Route::resource('manages/course', 'Admin\Manages\CourseController');
            Route::resource('manages/course.detail', 'Admin\Manages\CourseDetailController');
            Route::resource('manages/bill', 'Admin\Manages\BillController');
            Route::resource('manages/profile', 'Admin\Manages\ProfileController');
            Route::resource('manages/student', 'Admin\Manages\StudentController');
            Route::resource('manages/comment', 'Admin\Manages\CommentController');

        });
    });

    //user
    Route::group(['prefix' => 'user', 'middleware' => ['role:user|admin'], 'as' => 'user.'], function () {
        Route::resource('dashboard', 'User\DashboardController');
        Route::resource('course', 'User\CourseController');
        Route::resource('buy', 'User\BuyController');
        Route::resource('bill', 'User\BillController');
        Route::resource('status', 'User\StatusController');
        Route::resource('mycourse', 'User\MycourseController');
        Route::resource('class', 'User\ClassController');
        Route::resource('cart', 'User\CartController');
        Route::resource('study', 'User\StudyController');
        Route::resource('profile', 'User\ProfileController');
    });
});

app/CourseDetail.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CourseDetail extends Model
{
    public function course()
    {
        return $this->belongsTo(Course::class, 'course_id');
    }
}

app/Http/Controllers/Admin/Manages/CourseDetailController.php
<?php

namespace App\Http\Controllers\Admin\Manages;

use App\Course;
use App\CourseDetail;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CourseDetailController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($course_id)
    {
        $course = Course::find($course_id);
        $course_details = $course->course_details;
        return view('pages.admin.course_detail.index', compact('course', 'course_details'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($course_id)
    {
        $course = Course::find($course_id);
        return view('pages.admin.course_detail.create', compact('course'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $course_id)
    {
        DB::beginTransaction();
        $course_detail = new CourseDetail;
        $course_detail->course_id = $course_id;
        $course_detail->name = $request->name;
        $course_detail->detail = $request->detail;
        $course_detail->save();
        DB::commit();
        return redirect()->route('admin.manages.course.detail.index', $course_id)->with('message', 'สร้างบทเรียนสำเร็จ');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('pages.admin.course_detail.show');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($course_id, $course_detail_id)
    {
        $course_detail = CourseDetail::find($course_detail_id);
        return view('pages.admin.course_detail.edit', compact('course_detail'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $course_id, $course_detail_id)
    {
        DB::beginTransaction();
        $course_detail = CourseDetail::find($course_detail_id);
        $course_detail->name = $request->name;
        $course_detail->detail = $request->detail;
        $course_detail->save();
        DB::commit();
        return redirect()->route('admin.manages.course.detail.index', $course_id)->with('message', 'แก้ไขบทเรียนสำเร็จ');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($course_id, $course_detail_id)
    {
        DB::beginTransaction();
        $course_detail = CourseDetail::find($course_detail_id);
        $course_detail->delete();
        DB::commit();
        return redirect()->route('admin.manages.course.detail.index', $course_id)->with('message', 'ลบบทเรียนสำเร็จ');
    }
}

resources/views/pages/admin/course_detail/create.blade.php
@extends('layouts.admin.main')

@section('style')
<link href="/inspinia/css/plugins/iCheck/custom.css" rel="stylesheet">
<link href="/inspinia/css/plugins/summernote/summernote.css" rel="stylesheet">
<link href="/inspinia/css/plugins/summernote/summernote-bs3.css" rel="stylesheet">
@endsection

@section('list')
<div class="col-sm-12">
    <h2>สร้างคอร์สเรียน</h2>
    <ol class="breadcrumb">
        <li>
            <a>จัดการ</a>
        </li>
        <li>
            <a href="{{route('admin.manages.course.index')}}">คอร์สเรียนทั้งหมด</a>
        </li>

        <li>
            <a href="{{route('admin.manages.course.detail.index',$course->id)}}">{{$course->name}}</a>
        </li>

        <li class="active">
            <strong>สร้างบทเรียน</strong>
        </li>
    </ol>
</div>
@endsection
@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>สร้างบทเรียน</h5>
            </div>
            <div class="ibox-content">
                <form method="POST" action="{{route('admin.manages.course.detail.store',$course->id)}}" class="form-horizontal" enctype="multipart/form-data">
                    @csrf
                    
                    <div class="form-group"><label class="col-sm-2 control-label">ชื่อบทเรียน</label>
                        <div class="col-sm-10"><input type="text" name="name" class="form-control"></div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-2">
                            <button class="btn btn-white" type="reset">ยกเลิก</button>
                            <button class="btn btn-primary" type="submit">สร้างบทเรียน</button>
                        </div>
                    </div>        
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>เนื้อหาในบทเรียน</h5>
            </div>
            <div class="ibox-content no-padding">
                <textarea name="detail" class="summernote"></textarea>
            </div>
            </form>
        </div>
    </div>
</div>

@endsection

@section('script')
<script src="/inspinia/js/plugins/validate/jquery.validate.min.js"></script>
<script src="/inspinia/js/plugins/summernote/summernote.min.js"></script>
<script>
    $(document).ready(function () {
        $('.summernote').summernote({
            height: 300, //set editable area's height
            codemirror: { // codemirror options
                theme: 'monokai'
            }
        });
    });
</script>
@endsection

resources/views/pages/admin/course_detail/edit.blade.php
@extends('layouts.admin.main')

@section('style')
<link href="/inspinia/css/plugins/iCheck/custom.css" rel="stylesheet">
<link href="/inspinia/css/plugins/summernote/summernote.css" rel="stylesheet">
<link href="/inspinia/css/plugins/summernote/summernote-bs3.css" rel="stylesheet">
@endsection

@section('list')
<div class="col-sm-12">
    <h2>แก้ไขคอร์สเรียน</h2>
    <ol class="breadcrumb">
        <li>
            <a>จัดการ</a>
        </li>
        <li>
            <a href="{{route('admin.manages.course.index')}}">คอร์สเรียนทั้งหมด</a>
        </li>

        <li>
            <a href="{{route('admin.manages.course.detail.index',$course_detail->course_id)}}">{{$course_detail->course->name}}</a>
        </li>

        <li class="active">
            <strong>แก้ไขบทเรียน</strong>
        </li>
    </ol>
</div>
@endsection
@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>แก้ไขบทเรียน</h5>
            </div>
            <div class="ibox-content">
                <form method="POST" action="{{route('admin.manages.course.detail.update',[$course_detail->course_id,$course_detail->id])}}" class="form-horizontal" enctype="multipart/form-data">
                    @csrf @method('PATCH')
                    
                    <div class="form-group"><label class="col-sm-2 control-label">ชื่อบทเรียน</label>
                        <div class="col-sm-10"><input type="text" name="name" class="form-control" value="{{$course_detail->name}}"></div>
                    </div>

                    <div class="hr-line-dashed"></div>
                    <div class="form-group">
                        <div class="col-sm-4 col-sm-offset-2">
                            <button class="btn btn-white" type="reset">ยกเลิก</button>
                            <button class="btn btn-primary" type="submit">แก้ไขบทเรียน</button>
                        </div>
                    </div>        
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>เนื้อหาในบทเรียน</h5>
            </div>
            <div class="ibox-content no-padding">
                <textarea name="detail" class="summernote">{{$course_detail->detail}}</textarea>
            </div>
            </form>
        </div>
    </div>
</div>

@endsection

@section('script')
<script src="/inspinia/js/plugins/validate/jquery.validate.min.js"></script>
<script src="/inspinia/js/plugins/summernote/summernote.min.js"></script>
<script>
    $(document).ready(function () {
        $('.summernote').summernote({
            height: 300, //set editable area's height
            codemirror: { // codemirror options
                theme: 'monokai'
            }
        });
    });
</script>
@endsection

resources/views/pages/admin/course_detail/index.blade.php
@extends('layouts.admin.main')

@section('list')
<div class="col-sm-12">
    <h2>คอร์สเรียนทั้งหมด</h2>
    <ol class="breadcrumb">
        <li>
            <a>จัดการ</a>
        </li>
        <li>
            <a href="{{route('admin.manages.course.index')}}">คอร์สเรียนทั้งหมด</a>
        </li>

        <li class="active">
            <strong>{{$course->name}}</strong>
        </li>

    </ol>
</div>



@endsection

@section('style')

@endsection

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>รายการบทเรียนทั้งหมด</h5>
            </div>
            <div class="ibox-content">
                <div class="row">
                    <div class="col-sm-12">
                        <span class="pull-right">
                            <a href="{{route('admin.manages.course.detail.create',$course->id)}}" class="btn btn-sm btn-primary"> สร้างบทเรียน</a>
                        </span>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>ชื่อบทเรียน</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($course_details as $key =>$course_detail)
                                <tr>
                                    <th>{{$key+1}}</th>
                                    <td>{{$course_detail->name}}</td>
                                    <td>
                                        <a href="{{route('admin.manages.course.detail.edit',[$course->id,$course_detail->id])}}" class="btn btn-sm btn-primary">
                                            แก้ไขรายละเอียด</a>
                                        <form method="post" action="{{route('admin.manages.course.detail.destroy',[$course->id,$course_detail->id])}}"> 
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger">ลบบทเรียน</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>

</div>
@endsection

@section('script')

@endsection