routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */
Auth::routes();
Route::resource('/', 'DashboardController');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('home', 'HomeController');

    //admin
    Route::group(['prefix' => 'admin', 'middleware' => ['role:admin'], 'as' => 'admin.'], function () {
        Route::post('logout', 'Admin\DashboardController@logout')->name('logout');
        Route::resource('dashboard', 'Admin\DashboardController');

        Route::name('manages.')->group(function () {
            Route::resource('manages/course', 'Admin\Manages\CourseController');
            Route::resource('manages/course.detail', 'Admin\Manages\CourseDetailController');
            Route::resource('manages/bill', 'Admin\Manages\BillController');
            Route::resource('manages/profile', 'Admin\Manages\ProfileController');
            Route::resource('manages/student', 'Admin\Manages\StudentController');
            Route::resource('manages/comment', 'Admin\Manages\CommentController');

        });
    });

    //user
    Route::group(['prefix' => 'user', 'middleware' => ['role:user|admin'], 'as' => 'user.'], function () {
        Route::resource('dashboard', 'User\DashboardController');
        Route::resource('course', 'User\CourseController');
        Route::resource('buy', 'User\BuyController');
        Route::resource('bill', 'User\BillController');
        Route::resource('status', 'User\StatusController');
        Route::resource('mycourse', 'User\MycourseController');
        Route::resource('class', 'User\ClassController');
        Route::resource('cart', 'User\CartController');
        Route::resource('study', 'User\StudyController');
        Route::resource('profile', 'User\ProfileController');
    });
});

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    //
}

app/Http/Controllers/Admin/Manages/CommentController.php
<?php

namespace App\Http\Controllers\Admin\Manages;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('pages.admin.comment.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/admin/comment/index.blade.php
@extends('layouts.admin.main')

@section('list')
<div class="col-sm-12">
    <h2>แจ้งเตือนความคิดเห็น</h2>
    <ol class="breadcrumb">
        <li>
            <a>จัดการ</a>
        </li>
        <li class="active">
            <strong>ความคิดเห็น</strong>
        </li>
    </ol>
</div>
@endsection

@section('style')

@endsection

@section('content')
<div class="col-lg-12 animated fadeInRight">
    <div class="mail-box-header">
        <h2>
            กล่องความคิดเห็น (..)
        </h2>
        <div class="mail-tools tooltip-demo m-t-md">
            <div class="btn-group pull-right">
                <button class="btn btn-white btn-sm"><i class="fa fa-arrow-left"></i></button>
                <button class="btn btn-white btn-sm"><i class="fa fa-arrow-right"></i></button>

            </div>
            <button class="btn btn-white btn-sm" data-toggle="tooltip" data-placement="left" title="Refresh inbox"><i
                    class="fa fa-refresh"></i>Refresh</button>
            <button class="btn btn-white btn-sm" data-toggle="tooltip" data-placement="top" title="Mark as read"><i
                    class="fa fa-eye"></i> </button>
            <button class="btn btn-white btn-sm" data-toggle="tooltip" data-placement="top" title="Mark as important"><i
                    class="fa fa-exclamation"></i> </button>
            <button class="btn btn-white btn-sm" data-toggle="tooltip" data-placement="top" title="Move to trash"><i
                    class="fa fa-trash-o"></i> </button>

        </div>
    </div>
    <div class="mail-box">

        <table class="table table-hover table-mail">
            <tbody>
                <tr class="unread">
                    <td class="check-mail">
                        <input type="checkbox" class="i-checks">
                    </td>
                    <td class="mail-ontact"><a href={{route('user.study.show',2)}}>>Anna Smith</a></td>
                    <td class="mail-subject"><a href={{route('user.study.show',2)}}>"mail_detail.html">Lorem ipsum dolor noretek imit set.</a></td>
                    <td class=""><i class="fa fa-paperclip"></i></td>
                    <td class="text-right mail-date">6.10 AM</td>
                </tr>
                <tr class="unread">
                    <td class="check-mail">
                        <input type="checkbox" class="i-checks" checked>
                    </td>
                    <td class="mail-ontact"><a href="mail_detail.html">Jack Nowak</a></td>
                    <td class="mail-subject"><a href="mail_detail.html">Aldus PageMaker including versions of Lorem
                            Ipsum.</a></td>
                    <td class=""></td>
                    <td class="text-right mail-date">8.22 PM</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>

@endsection

@section('script')

@endsection